### ISSUE TITLE
Problems using Async

### ISSUE THREAD

**Issue by JoshHunger** [zf-fr/zfr-mailchimp#24]
When I use the subscribe method using the Guzzle library for an Async request I do not see a new subscriber in my Mailchimp list. There is no error, and the request even gets a 200 status response. 

Everything works fine when I'm making a synchronous request. I'm using the Symfony2 bundle btw(default config).

Any ideas where to start looking?

**Comment by bakura10** [comment]
Hi,

I should update the documentation, but you should not use the Async plugin. It has been known in Guzzle that Async plugin is very... strange and often does not work as expected. Guzzle 5 does not have async plugin for instance (but other mechanism).

I'll likely update ZfrMailChimp to Guzzle 5 once it stabilizes, but in the mean time, I'd suggest you not using Async. If you have the possibility to do this, I recommend instead of using a queue system if doing a sync API call is too expensive.

**Comment by bakura10** [comment]
I've updated the doc to include the warning.
